chore: 빌드 방식 업데이트

diff --git a/.github/workflows/docker-cicd.yml b/.github/workflows/docker-cicd.yml
--- a/.github/workflows/docker-cicd.yml
+++ b/.github/workflows/docker-cicd.yml
@@ -14,19 +14,35 @@ jobs:
     steps:
     - uses: actions/checkout@v3
 
+    - name: Extract version from pyproject.toml
+      id: get_version
+      run: echo "VERSION=$(grep '^version =' pyproject.toml | sed -E 's/version = \"(.*)\"/\1/')" >> $GITHUB_ENV
+
     - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v3
+      uses: docker/setup-buildx-action@v2
 
     - name: Build Docker image
-      run: docker build -t myapp -f Dockerfile .
+      run: docker build -t myapp:${{ env.VERSION }} -f Dockerfile .
 
     - name: Run Docker container
-      run: docker run -d -p 5000:5000 myapp
+      run: docker run -d -p 5000:5000 --name myapp-container myapp:${{ env.VERSION }}
 
-    - name: Test
+    - name: health check
       run: |
-        sleep 100
-        curl http://localhost:5000/health
+          for i in {0..6}; do
+            curl -f http://localhost:5000/health && exit 0
+            echo "Attempt $i failed, waiting 9 seconds..."
+            sleep 9
+          done
+          exit 1
+
+    - name: Show Docker logs on Test failure
+      if: failure()
+      run: |
+          echo "=== Docker Container Status ==="
+          docker ps -a
+          echo "=== Docker Container Logs ==="
+          docker logs myapp-container
 
     - name: action-slack
       uses: 8398a7/action-slack@v3
@@ -64,6 +80,8 @@ jobs:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: |
           cd ~/docker/basic_ml_api
+          echo "LOG_LEVEL=${{ vars.LOG_LEVEL }}" > .env
+          echo "VERSION=${{ env.VERSION }}" >> .env
           docker compose down --rmi all
           docker compose build --no-cache
           docker compose up -d
